### ISSUE TITLE
View command on directories

### ISSUE THREAD

**Issue by alexandremello** [erickzanardo/git-cutlass#1]
Hi!

It crashes when I execute the `View` command on a directory object. I think is not necessary the `View` command when the object is a  directory.

**Comment by erickzanardo** [comment]
This was fixed with a tempory solution for 1.0.4. When viewing a folder a message "The folder /foo/bar was added" will be showed on the diff view. For a next release, when viewing a new folder, the content of all it's files will be show on the diff view.
